os: osx
osx_image: xcode12
language: generic

addons:
  homebrew:
    packages:
      - gradle
    casks:
      - google-chrome
    update: true


branches:
  only:
    - master
    - develop
    - /^[0-9].[0-9].[0-9]$/

git:
  depth: 3


before_install:
  - gradle -b wrapper.gradle


before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache


script: ./gradlew build check


env:
  global:
    - ORG_GRADLE_PROJECT_version=$TRAVIS_TAG
    - TERM=dumb
