name: Build

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 15
      - run: gradle -b wrapper.gradle
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build
